//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurageSnap.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BurageSnap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Extract error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Capture_Extract_error {
            get {
                return ResourceManager.GetString("Capture_Extract_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Capture_Internal_error {
            get {
                return ResourceManager.GetString("Capture_Internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Capture_Search_error {
            get {
                return ResourceManager.GetString("Capture_Search_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap cogs {
            get {
                object obj = ResourceManager.GetObject("cogs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Output the images? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmView_Message {
            get {
                return ResourceManager.GetString("ConfirmView_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmView_No {
            get {
                return ResourceManager.GetString("ConfirmView_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmView_Title {
            get {
                return ResourceManager.GetString("ConfirmView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmView_Yes {
            get {
                return ResourceManager.GetString("ConfirmView_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap folder_open_16 {
            get {
                object obj = ResourceManager.GetObject("folder_open_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Capture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Capture {
            get {
                return ResourceManager.GetString("MainWindow_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Burst に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Continuous {
            get {
                return ResourceManager.GetString("MainWindow_Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last snap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Last_snap {
            get {
                return ResourceManager.GetString("MainWindow_Last_snap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Start {
            get {
                return ResourceManager.GetString("MainWindow_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_Stop {
            get {
                return ResourceManager.GetString("MainWindow_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_Exit {
            get {
                return ResourceManager.GetString("NotifyIcon_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_Open {
            get {
                return ResourceManager.GetString("NotifyIcon_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Add {
            get {
                return ResourceManager.GetString("OptionView_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Animation GIF (Burst) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Animation_GIF {
            get {
                return ResourceManager.GetString("OptionView_Animation_GIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Cancel {
            get {
                return ResourceManager.GetString("OptionView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create daily folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Create_daily_folders {
            get {
                return ResourceManager.GetString("OptionView_Create_daily_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Folder {
            get {
                return ResourceManager.GetString("OptionView_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Format {
            get {
                return ResourceManager.GetString("OptionView_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   frames に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Frames {
            get {
                return ResourceManager.GetString("OptionView_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hot key: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Hot_key {
            get {
                return ResourceManager.GetString("OptionView_Hot_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Interval {
            get {
                return ResourceManager.GetString("OptionView_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Option {
            get {
                return ResourceManager.GetString("OptionView_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pick window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Pick_window {
            get {
                return ResourceManager.GetString("OptionView_Pick_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Remove {
            get {
                return ResourceManager.GetString("OptionView_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reside in system tray に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Reside_in_system_tray {
            get {
                return ResourceManager.GetString("OptionView_Reside_in_system_tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ring buffer: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Ring_buffer {
            get {
                return ResourceManager.GetString("OptionView_Ring_buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target windows: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Target_windows {
            get {
                return ResourceManager.GetString("OptionView_Target_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top most に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Top_most {
            get {
                return ResourceManager.GetString("OptionView_Top_most", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionView_Window {
            get {
                return ResourceManager.GetString("OptionView_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I/O error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Recorder_IO_error {
            get {
                return ResourceManager.GetString("Recorder_IO_error", resourceCulture);
            }
        }
    }
}
